<?php use Phalcon\Tag; ?>
<?php
foreach($sentences as $sentence) {
    if ($sentence->tag){
        echo "<div class=sentarea_{$sentence->tag}>";
    }else{
        echo "<div class=sentarea>";
    }
    echo "<div class=sentence>&nbsp;&nbsp;";
    echo $sentence->text;
    echo "</div>";
    echo "<div class=date>";
    if ($sentence->tag)  {
        echo "tag: " . $sentence->tag . "&nbsp&nbsp&nbsp&nbsp";
    }
    echo date("Y年m月d日 H:i", $sentence->_t);
    if ($editable){
        echo "<input type=hidden name=id value=";
        echo $sentence->_id;
        echo " />";
    }
    echo "</div>";
    if ($editable){
        echo "<div class=mv-del title=删除此条></div>";
    }
    echo "</div>";
}
?>

